package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the vcsRoot with id = 'BotHandly'
accordingly, and delete the patch script.
*/
changeVcsRoot(RelativeId("BotHandly")) {
    val expected = GitVcsRoot({
        id("BotHandly")
        name = "bot-handly"
        url = "git@github.com:Zarckir/bot-handly.git"
        branch = "refs/heads/master"
        branchSpec = """
            +:refs/heads/*
            +:refs/tags/*
        """.trimIndent()
        useTagsAsBranches = true
        authMethod = uploadedKey {
            uploadedKey = "id_ed25519_github"
        }
    })

    check(this == expected) {
        "Unexpected VCS root settings"
    }

    (this as GitVcsRoot).apply {
        authMethod = uploadedKey {
            userName = ""
            uploadedKey = "github"
            passphrase = ""
        }
    }

}
